### ISSUE TITLE
Feature: Creare menù iniziale

### ISSUE THREAD

**Issue by gallottino** [Sibrox/HexagonGlass#31]
**Descrizione**:
Creare un nuovo screen che permetta all'utente di mouversi tra Gioca, Settings, Tutorial e Infinity Mode.

**Todo list**:

- [ ] Creare design Figma (#44) 
- [ ] Aggiungere pulsante "Gioca" (decidere nome) e linkarlo a screen `Menù` (Navigator.push)
- [ ] Aggiungere pulsante "Infinity" (decidere nome) e linkarlo a screen `InfinityLevel`   (#41)
- [ ] Aggiungere pulsante "Settings" e linkarlo a screen `Settings` (#42)
- [ ] Aggiungere pulsante "Tutorial" e linkarlo a screen `Tutorial`

**Informazioni**:
